import Head from "next/head";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/profile-picture.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import countries from "../public/Countries.png";
import walletwise from "../public/walletwiseAdmin.jpeg";
import soon from "../public/coming-soon.jpg";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""} width>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-24 sm:px8 lg:px-40  hover:scroll-auto">
        <section className="min-h-screen">
          <nav className="py-10 mb-8 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyGC</h1>
            <ul className="flex items-center">
              <li>
                {darkMode ? (
                  <BsFillSunFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-2xl hover:animate-spin"
                  />
                ) : (
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-2xl hover:animate-spin"
                  />
                )}
              </li>
              <li>
                <button
                  className="transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-cyan-700 duration-300 bg-gradient-to-r from-cyan-800 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="../public/cv.pdf"
                  download
                >
                  Resume / CV
                </button>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Gianluca Cianchi
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Full Stack Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Full Stack Developer providing services for programming and needs.
              Join me down below and let&apos;s get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                href="https://www.linkedin.com/in/gianluca-cianchi"
                target="_blank"
                rel="noreferrer"
              >
                <AiFillLinkedin />
              </a>
              <a
                href="https://github.com/Ezeko95"
                target="blank"
                rel="noreferrer"
              >
                <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80  overflow-hidden mt-10 sm:w-72 sm:h-72 md:h-96 md:w-96 animate-jump-in animate-duration-[5000ms]">
              <Image
                src={deved}
                className=""
                layout="fill"
                objectFit="cover"
                alt="profile"
              />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              As a full stack developer, I provide comprehensive web development
              services encompassing both front-end and back-end development.
              With expertise in{" "}
              <span className="text-teal-500"> Javascript/Typescript</span>,
              frameworks like{" "}
              <span className="text-teal-500">
                {" "}
                React, Express and Sequelize,{" "}
              </span>
              and other technologies. I specialize in creating dynamic and
              interactive web applications that meet the specific needs of my
              clients. I ensure seamless functionality and an exceptional user
              experience. I also handle tasks such as{" "}
              <span className="text-teal-500"> API </span>
              development, third-party integrations, performance optimization,
              and bug fixing. With a focus on delivering{" "}
              <span className="text-teal-500">
                {" "}
                high-quality, scalable, and maintainable solutions.{" "}
              </span>{" "}
              I strive to help businesses thrive in the digital realm.
            </p>
            <h3 className="text-3xl py-1 dark:text-white ">My soft skills</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              As a full stack developer, possessing a combination of technical
              expertise and essential soft skills is key to success.{" "}
              <span className="text-teal-500"> Strong communication </span> and
              <span className="text-teal-500">
                {" "}
                problem-solving abilities
              </span>{" "}
              allow me to collaborate effectively with teams and understand
              client requirements. I thrive in dynamic environments, adapting
              quickly to new technologies and learning opportunities. With
              excellent time management and attention to detail. Working
              seamlessly within multidisciplinary teams, I contribute ideas and
              support colleagues to achieve shared goals. Continuously learning
              and embracing creativity, I approach challenges with innovation,
              resulting in exceptional web applications.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-2xl shadow-teal-500 p-10 rounded-xl my-10 bg-yellow-50 dark:bg-cyan-200 flex-1 animate-wiggle animate-infinite animate-duration-[10000ms] animate-ease-in animate-normal animate-fill-both ">
              <Image src={design} width={100} height={100} alt="designs" />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Full Stack Web Development
              </h3>
              <p className="py-2">
                I offer end-to-end web development solutions, creating elegant
                and functional websites and applications.
              </p>
              <h4 className="py-4 text-teal-600">
                Tools and Technologies I Use
              </h4>
              <div className="flex flex-wrap">
                <div className="w-1/2">
                  <p className="text-gray-800 py-1">JavaScript/TypeScript</p>
                  <p className="text-gray-800 py-1">React Native</p>
                  <p className="text-gray-800 py-1">React</p>
                  <p className="text-gray-800 py-1">HTML5</p>
                  <p className="text-gray-800 py-1">Tailwind CSS</p>
                </div>
                <div className="w-1/2">
                  <p className="text-gray-800 py-1">Express.js</p>
                  <p className="text-gray-800 py-1">Node.js</p>
                  <p className="text-gray-800 py-1">Sequelize</p>
                  <p className="text-gray-800 py-1">PostgreSQL</p>
                  <p className="text-gray-800 py-1">JSON Web Tokens</p>
                  <p className="text-gray-800 py-1">Bcrypt</p>
                </div>
              </div>
            </div>
            <div className="text-center shadow-2xl shadow-teal-500  p-10 rounded-xl my-10 bg-yellow-50 dark:bg-cyan-200 flex-1 animate-wiggle animate-infinite animate-duration-[10000ms] animate-ease-in animate-normal animate-fill-both">
              <Image src={code} width={100} height={100} alt="design" />
              <h3 className="text-lg font-medium pt-8 pb-2">Custom Coding</h3>
              <p className="py-2">
                Let&apos;s bring your dream project to life! I specialize in
                developing custom websites and applications tailored to your
                specific requirements.
              </p>
              <h4 className="py-4 text-teal-600">Services I Offer</h4>
              <p className="text-gray-800 py-1">Front-end Development</p>
              <p className="text-gray-800 py-1">Back-end Development</p>
              <p className="text-gray-800 py-1">Database Integration</p>
              <p className="text-gray-800 py-1">API Development</p>
            </div>
            <div className="text-center shadow-2xl shadow-teal-500  p-10 rounded-xl my-10 bg-yellow-50 dark:bg-cyan-200 flex-1 animate-wiggle animate-infinite animate-duration-[10000ms] animate-ease-in animate-normal animate-fill-both">
              <Image src={consulting} width={100} height={100} alt="design" />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Consulting and Advice
              </h3>
              <p className="py-2">
                Need guidance on your current project? I offer consulting
                services to help optimize and enhance your web development
                projects.
              </p>
              <h4 className="py-4 text-teal-600">Services I Offer</h4>
              <p className="text-gray-800 py-1">Code Review and Optimization</p>
              <p className="text-gray-800 py-1">Technical Consulting</p>
              <p className="text-gray-800 py-1">
                Project Planning and Strategy
              </p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Throughout my journey as a full stack web developer, I have gained
              valuable experience working on various projects. I have
              collaborated with a startup, with project groups, and talented
              individuals to create digital products for both business and
              consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              My services encompass a wide range of expertise, including brand
              design and programming. I have a passion for delivering
              high-quality solutions that meet the unique needs of each client.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 hover:shadow-2xl hover:shadow-black dark:hover:shadow-white transition duration-500">
              <a
                href="https://drive.google.com/file/d/1vjRHHm_7KiXtfaaqAuyX3MXGXT_q2Dpi/view"
                target="_blank"
                rel="noreferrer"
                className="rounded-lg overflow-hidden"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={"50%"}
                  height={"50%"}
                  layout="responsive"
                  alt="walletwise"
                  src={walletwise}
                />
              </a>
            </div>
            <h1>PI-Countries</h1>
            <div className="basis-1/3 flex-1 hover:shadow-2xl hover:shadow-black dark:hover:shadow-white transition duration-500">
              <a
                href="https://proyecto-individual-countries-f6ys3wr88-ezeko95.vercel.app/?vercelToolbarCode=0g9cxBGljsKxEnf"
                target="_blank"
                rel="noreferrer"
                className="rounded-lg overflow-hidden"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={"50%"}
                  height={"50%"}
                  layout="responsive"
                  alt="countries"
                  src={countries}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 hover:shadow-2xl hover:shadow-black dark:hover:shadow-white">
              <Image
                className="rounded-lg object-contain"
                width={"30%"}
                height={"30%"}
                layout="responsive"
                alt="soon"
                src={soon}
              />
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-2xl">Let&apos;s keep in touch!</h2>
          <h4>Send me an email down below if you enjoyed my work.</h4>
          <form>
            <label>Email: </label>
            <input type="text" class="rounded text-pink-500"/>
            <label></label>
          </form>
        </section>
      </main>
    </div>
  );
}
